# Generated by Django 5.0.4 on 2024-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_comment='Email', help_text='Email', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
